#ligação a base de dados
spring.application.name=splitwise-api

# Configuração da base de dados H2 (em memória)
spring.datasource.url=jdbc:h2:mem:splitwise
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite aceder à consola web do H2 para ver as tabelas visualmente
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Diz ao Hibernate para criar ou atualizar as tabelas automaticamente a partir das entidades
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal o SQL que o Hibernate está a gerar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081