spring.datasource.url=jdbc:postgresql://localhost:5432/splitwise
spring.datasource.username=${DB_USERNAME:splitwise}
spring.datasource.password=${DB_PASSWORD:splitwise}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081